### ISSUE TITLE
匹配路由规则需要限定调用的函数

### ISSUE THREAD

**Issue by likfe** [fashare2015/SmallHelper-IDEA-Plugin#1]
如图，只要是字符串都给匹配了：

![wechatimg31](https://user-images.githubusercontent.com/7094014/31987051-272df390-b99d-11e7-888f-4a438aee1fb0.jpeg)

---

![wechatimg32](https://user-images.githubusercontent.com/7094014/31987055-2bb4bba6-b99d-11e7-99f7-b44a62b0ca3c.jpeg)

😅

**Comment by fashare2015** [comment]
老铁所言甚是，还得想想要怎么弄😅
